version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: script/reload-pm2.sh
      timeout: 300
      runas: ubuntu
